In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

In [2]:
df = pd.read_excel("关于婚育意愿的调查.xlsx")

In [3]:
df = pd.concat([df[df["21、您的性别"]=="男" ][:200],df[df["21、您的性别"]=="女"][:200]],axis = 0)

In [4]:
df.to_csv('sample200.csv')

## 1、性别和结婚意愿

In [5]:
df1 = df[["21、您的性别","3、请问您的结婚意愿为","所用时间"]]

In [6]:
df1_res = pd.crosstab(df1["21、您的性别"],df1["3、请问您的结婚意愿为"],margins=True)
df1_res

3、请问您的结婚意愿为  不会，但接受同居  不会，打算单身  不知道，顺其自然  有结婚打算  All
21、您的性别                                             
女                  22       18        97     63  200
男                  18       15        68     99  200
All                40       33       165    162  400

In [7]:
import numpy as np
df1_chi = np.array([df1_res.iloc[0][0:4],df1_res.iloc[1][0:4]])
df1_chi

array([[22, 18, 97, 63],
       [18, 15, 68, 99]], dtype=int64)

In [8]:
from scipy import stats

In [9]:
stats.chi2_contingency(df1_chi)[:3]

(13.76969696969697, 0.003236000282935631, 3)

## p值小于0.05，拒绝了性别和结婚意愿具有独立性的原假设，通过列联表可以明显看出男性比女性的结婚意愿更强，女性更多地选择了顺其自然。

## 2、性别和恋爱状态

In [10]:
df2 = df[["21、您的性别","1、请问您目前的恋爱状态为","所用时间"]]

In [11]:
df2_res = pd.crosstab(df2["21、您的性别"],df2["1、请问您目前的恋爱状态为"],margins=True)
df2_res

1、请问您目前的恋爱状态为  单身，无恋爱打算  单身，有恋爱打算  正在恋爱中  All
21、您的性别                                      
女                    76        58     66  200
男                    71        82     47  200
All                 147       140    113  400

In [12]:
df2_chi = np.array([df2_res.iloc[0][0:3],df2_res.iloc[1][0:3]])
df2_chi

array([[76, 58, 66],
       [71, 82, 47]], dtype=int64)

In [13]:
stats.chi2_contingency(df2_chi)[:3]

(7.479044006983324, 0.023765460223769488, 2)

## 3、性别和促进因素

In [14]:
df3= df[["21、您的性别","5、请问您认为或您见到的促进结婚的因素有哪些","所用时间"]]

In [15]:
dic3 = {"性别":[],"促进因素":[],"所用时间":[]}

In [16]:
df3

21、您的性别                             5、请问您认为或您见到的促进结婚的因素有哪些  所用时间
0         男         婚姻能够提供情感、陪伴或精神寄托┋婚姻可以带来物质经济保障┋来自长辈的压力┋生理需求  250秒
1         男                 婚姻能够提供情感、陪伴或精神寄托┋婚姻是人生的必需项┋来自长辈的压力  183秒
2         男                     婚姻能够提供情感、陪伴或精神寄托┋有生儿育女的期望┋生理需求  166秒
3         男                         婚姻能够提供情感、陪伴或精神寄托┋婚姻是人生的必需项  170秒
6         男                         婚姻能够提供情感、陪伴或精神寄托┋婚姻是人生的必需项  180秒
..      ...                                                ...   ...
487       女            婚姻能够提供情感、陪伴或精神寄托┋婚姻是人生的必需项┋婚姻可以带来物质经济保障  228秒
492       女                     婚姻能够提供情感、陪伴或精神寄托┋生理需求┋其他〖足够喜欢〗  357秒
494       女                              婚姻能够提供情感、陪伴或精神寄托┋生理需求  267秒
502       女  婚姻能够提供情感、陪伴或精神寄托┋婚姻是人生的必需项┋有生儿育女的期望┋婚姻可以带来物质经济...  200秒
506       女                                   婚姻能够提供情感、陪伴或精神寄托   84秒

[400 rows x 3 columns]

In [17]:
df3.iloc[0,1].split("┋"),df3.shape

(['婚姻能够提供情感、陪伴或精神寄托', '婚姻可以带来物质经济保障', '来自长辈的压力', '生理需求'], (400, 3))

In [18]:
for i in range(df3.shape[0]):
    if "其他" not in df3.iloc[i,1]:
        alis = df3.iloc[i,1].split("┋")
        for a in alis:
            dic3["性别"].append(df3.iloc[i,0])
            dic3["促进因素"].append(a)
            dic3["所用时间"].append(df3.iloc[i,2])

In [19]:
df3_ = pd.DataFrame(dic3)
df3_

性别              促进因素  所用时间
0    男  婚姻能够提供情感、陪伴或精神寄托  250秒
1    男      婚姻可以带来物质经济保障  250秒
2    男           来自长辈的压力  250秒
3    男              生理需求  250秒
4    男  婚姻能够提供情感、陪伴或精神寄托  183秒
..  ..               ...   ...
988  女         婚姻是人生的必需项  200秒
989  女          有生儿育女的期望  200秒
990  女      婚姻可以带来物质经济保障  200秒
991  女              生理需求  200秒
992  女  婚姻能够提供情感、陪伴或精神寄托   84秒

[993 rows x 3 columns]

In [20]:
df3_.to_csv('促进因素.csv')

In [122]:
df3_res = pd.crosstab(df3_["性别"],df3_["促进因素"],margins=True)
df3_res

促进因素  为了获得婚育政策上的优待  婚姻可以带来物质经济保障  婚姻是人生的必需项  婚姻能够提供情感、陪伴或精神寄托  有生儿育女的期望  \
性别                                                                        
女               18            60         31               165        47   
男               14            47         63               166        81   
All             32           107         94               331       128   

促进因素  来自同龄人的压力  来自长辈的压力  生理需求  All  
性别                                  
女           25       66    44  456  
男           25       64    77  537  
All         50      130   121  993

In [125]:
df3_chi = np.array([df3_res.iloc[0][0:8],df3_res.iloc[1][0:8]])
df3_chi

array([[ 18,  60,  31, 165,  47,  25,  66,  44],
       [ 14,  47,  63, 166,  81,  25,  64,  77]], dtype=int64)

In [126]:
stats.chi2_contingency(df3_chi)[:3]

(24.594493414948055, 0.000895143492363509, 7)

## 4、性别和抑制因素

In [21]:
df4 = df[["21、您的性别","6、请问您认为或您见到的抑制结婚的因素有哪些","所用时间"]]

In [22]:
dic4 = {"性别":[],"抑制因素":[],"所用时间":[]}

In [23]:
for i in range(df4.shape[0]):
    if "其他" not in df4.iloc[i,1]:
        alis = df4.iloc[i,1].split("┋")
        for a in alis:
            dic4["性别"].append(df4.iloc[i,0])
            dic4["抑制因素"].append(a)
            dic4["所用时间"].append(df4.iloc[i,2])

In [24]:
df4_ = pd.DataFrame(dic4)
df4_

性别               抑制因素  所用时间
0     男             结婚成本较高  250秒
1     男             生育成本较高  250秒
2     男        工作压力和社会压力较大  250秒
3     男      现代人享受单身生活的自由感  250秒
4     男  对于照料双方父母、子女等事宜的担忧  250秒
...  ..                ...   ...
2035  女             生育成本较高  200秒
2036  女        工作压力和社会压力较大  200秒
2037  女             结婚成本较高   84秒
2038  女             生育成本较高   84秒
2039  女        工作压力和社会压力较大   84秒

[2040 rows x 3 columns]

In [25]:
df4_.to_csv('抑制因素.csv')

In [11]:
df4_res = pd.crosstab(df4_["性别"],df4_["抑制因素"],margins=True)
df4_res

抑制因素  对于照料双方父母、子女等事宜的担忧  对于结婚本身欲望较低  工作压力和社会压力较大  父母长辈对子女伴侣要求较高  \
性别                                                                
女                    88          94          131             45   
男                    65          63          145             50   
All                 153         157          276             95   

抑制因素  现代人享受单身生活的自由感  生育成本较高  社会对于不婚等现象越来越包容  离婚成本较高  结婚成本较高  难以找到物质条件上满意的结婚对象  \
性别                                                                              
女               119     138              69      70     114                90   
男                95     142              46      33     144                49   
All             214     280             115     103     258               139   

抑制因素  难以找到观念、生活方式都契合的对象   All  
性别                             
女                   141  1099  
男                   109   941  
All                 250  2040

In [15]:
df4_chi = np.array([df4_res.iloc[0][0:11],df4_res.iloc[1][0:11]])
df4_chi

array([[ 88,  94, 131,  45, 119, 138,  69,  70, 114,  90, 141],
       [ 65,  63, 145,  50,  95, 142,  46,  33, 144,  49, 109]],
      dtype=int64)

In [16]:
stats.chi2_contingency(df4_chi)[:3]

(38.865615815362055, 2.6801559920722607e-05, 10)

## 5.1 性别和婚前同居

In [36]:
def cross_ananlysis(var):
    dff = df[["21、您的性别",var,"所用时间"]]
    dff_res = pd.crosstab(dff["21、您的性别"],dff[var],margins=True)
    dff_chi = np.array([dff_res.iloc[0][0:(dff_res.shape[1]-1)],dff_res.iloc[1][0:(dff_res.shape[1]-1)]])
    return dff_res,dff_chi,stats.chi2_contingency(dff_chi)[:3]
    

In [37]:
df5_1_res,df5_1_chi,df5_1_ana = cross_ananlysis("7、请问您对于以下婚姻行为的认同度为—婚前同居")

In [38]:
df5_1_res

7、请问您对于以下婚姻行为的认同度为—婚前同居  不太认同  不认同   认同  较认同  All
21、您的性别                                          
女                          26   21   82   71  200
男                          27   16   90   67  200
All                        53   37  172  138  400

In [39]:
df5_1_chi

array([[26, 21, 82, 71],
       [27, 16, 90, 67]], dtype=int64)

In [40]:
df5_1_ana

(1.1825786524452988, 0.7571856310825741, 3)

## 5.2 性别和婚前性行为

In [41]:
df5_2_res,df5_2_chi,df5_2_ana = cross_ananlysis("7、婚前性行为")

In [42]:
df5_2_res

7、婚前性行为  不太认同  不认同   认同  较认同  All
21、您的性别                          
女          37   28   81   54  200
男          39   14   88   59  200
All        76   42  169  113  400

In [43]:
df5_2_chi

array([[37, 28, 81, 54],
       [39, 14, 88, 59]], dtype=int64)

In [45]:
df5_2_ana

(5.230478012069499, 0.15567771601131553, 3)

## 5.3 性别和不婚（有关联）

In [46]:
df5_3_res,df5_3_chi,df5_3_ana = cross_ananlysis("7、不婚")

In [48]:
df5_3_res

7、不婚     不太认同  不认同   认同  较认同  All
21、您的性别                          
女          26    8  107   59  200
男          55   38   64   43  200
All        81   46  171  102  400

In [49]:
df5_3_chi

array([[ 26,   8, 107,  59],
       [ 55,  38,  64,  43]], dtype=int64)

In [50]:
df5_3_ana

(43.27060285933172, 2.156027923724087e-09, 3)

## 5.4性别和丁克（有关联）

In [51]:
df5_4_res,df5_4_chi,df5_4_ana = cross_ananlysis("7、丁克（不生孩子）")

In [52]:
df5_4_res

7、丁克（不生孩子）  不太认同  不认同   认同  较认同  All
21、您的性别                             
女             29    9  110   52  200
男             44   47   63   46  200
All           73   56  173   98  400

In [53]:
df5_4_chi

array([[ 29,   9, 110,  52],
       [ 44,  47,  63,  46]], dtype=int64)

In [54]:
df5_4_ana

(42.00403913247934, 4.004216035787537e-09, 3)

## 5.5 性别和同性恋行为（有关联）

In [55]:
df5_5_res,df5_5_chi,df5_5_ana = cross_ananlysis("7、同性恋行为")

In [56]:
df5_5_res

7、同性恋行为  不太认同  不认同   认同  较认同  All
21、您的性别                          
女          28    5  101   66  200
男          42   75   41   42  200
All        70   80  142  108  400

In [57]:
df5_5_chi

array([[ 28,   5, 101,  66],
       [ 42,  75,  41,  42]], dtype=int64)

In [58]:
df5_5_ana

(94.73544600938968, 2.104599231139597e-20, 3)

## 5.6 性别和闪婚行为

In [60]:
df5_6_res,df5_6_chi,df5_6_ana = cross_ananlysis("7、闪婚行为")

In [61]:
df5_6_res

7、闪婚行为   不太认同  不认同  认同  较认同  All
21、您的性别                         
女         101   37  27   35  200
男          71   78  27   24  200
All       172  115  54   59  400

In [62]:
df5_6_chi

array([[101,  37,  27,  35],
       [ 71,  78,  27,  24]], dtype=int64)

In [63]:
df5_6_ana

(21.90079690150983, 6.84060100840436e-05, 3)

## 5.7 性别和非婚生育

In [65]:
df5_7_res,df5_7_chi,df5_7_ana = cross_ananlysis("7、非婚生育")

In [66]:
df5_7_res

7、非婚生育   不太认同  不认同  认同  较认同  All
21、您的性别                         
女          74   68  34   24  200
男          62   98  25   15  200
All       136  166  59   39  400

In [67]:
df5_7_chi

array([[74, 68, 34, 24],
       [62, 98, 25, 15]], dtype=int64)

In [68]:
df5_7_ana

(9.930314709254997, 0.019167868941997433, 3)

## 5.8 性别和堕胎

In [69]:
df5_8_res,df5_8_chi,df5_8_ana = cross_ananlysis("7、堕胎")

In [70]:
df5_8_res

7、堕胎     不太认同  不认同   认同  较认同  All
21、您的性别                          
女          51   44   59   46  200
男          52   80   42   26  200
All       103  124  101   72  400

In [71]:
df5_8_chi

array([[51, 44, 59, 46],
       [52, 80, 42, 26]], dtype=int64)

In [72]:
df5_8_ana

(18.878263335259298, 0.00028971028170090435, 3)

## 5.9 性别和开放性关系

In [73]:
df5_9_res,df5_9_chi,df5_9_ana = cross_ananlysis("7、开放性关系")

In [74]:
df5_9_res

7、开放性关系  不太认同  不认同  认同  较认同  All
21、您的性别                         
女          66   70  30   34  200
男          50   94  34   22  200
All       116  164  64   56  400

In [75]:
df5_9_chi

array([[66, 70, 30, 34],
       [50, 94, 34, 22]], dtype=int64)

In [76]:
df5_9_ana

(8.540520245103929, 0.036066824875185435, 3)

## 6.1 意愿子女数

In [77]:
df6_1_res,df6_1_chi,df6_1_ana = cross_ananlysis("8、请填写您的理想及意愿的子女数—意愿子女数（考虑物质经济等因素）")

In [78]:
df6_1_res

8、请填写您的理想及意愿的子女数—意愿子女数（考虑物质经济等因素）    0    1    2  3  4个及以上  All
21、您的性别                                                        
女                                   71   87   39  0      3  200
男                                   38   78   78  3      3  200
All                                109  165  117  3      6  400

In [79]:
df6_1_chi

array([[71, 87, 39,  0,  3],
       [38, 78, 78,  3,  3]], dtype=int64)

In [80]:
df6_1_ana

(26.481734778982485, 2.5298851129093586e-05, 4)

## 6.2 理想子女数

In [81]:
df6_2_res,df6_2_chi,df6_2_ana = cross_ananlysis("8、理想子女数（不考虑任何因素时）")

In [82]:
df6_2_res

8、理想子女数（不考虑任何因素时）   0   1    2   3  4个及以上  All
21、您的性别                                       
女                  58  42   91   4      5  200
男                  24  34  121  15      6  200
All                82  76  212  19     11  400

In [83]:
df6_2_chi

array([[ 58,  42,  91,   4,   5],
       [ 24,  34, 121,  15,   6]], dtype=int64)

In [84]:
df6_2_ana

(25.64427940117625, 3.732422165821706e-05, 4)

## 6.3 理想儿子数

In [85]:
df6_3_res,df6_3_chi,df6_3_ana = cross_ananlysis("8、理想生儿子的个数")

In [86]:
df6_3_res

8、理想生儿子的个数    0    1  2  3  4个及以上  All
21、您的性别                               
女            95  103  0  1      1  200
男            43  145  8  0      4  200
All         138  248  8  1      5  400

In [87]:
df6_3_chi

array([[ 95, 103,   0,   1,   1],
       [ 43, 145,   8,   0,   4]], dtype=int64)

In [88]:
df6_3_ana

(37.50710612435718, 1.4160565994404123e-07, 4)

## 6.4 理想女儿数

In [90]:
df6_4_res,df6_4_chi,df6_4_ana = cross_ananlysis("8、理想生女儿的个数")

In [91]:
df6_4_res

8、理想生女儿的个数   0    1   2  3  4个及以上  All
21、您的性别                               
女           57  134   5  1      3  200
男           26  161  11  0      2  200
All         83  295  16  1      5  400

In [92]:
df6_4_chi

array([[ 57, 134,   5,   1,   3],
       [ 26, 161,  11,   0,   2]], dtype=int64)

In [93]:
df6_4_ana

(17.499499693690016, 0.0015453448048094454, 4)

## 7、见到的阻碍生育的因素

In [5]:
def cross_analysis2(var,useless,splitt):
    dff = df[["21、您的性别",var,"所用时间"]]
    dic = {"性别":[],var:[],"所用时间":[]}
    for i in range(dff.shape[0]):
        if useless not in dff.iloc[i,1]:
            alis = dff.iloc[i,1].split(splitt)
            for a in alis:
                dic["性别"].append(dff.iloc[i,0])
                dic[var].append(a)
                dic["所用时间"].append(dff.iloc[i,2])
    dff_ = pd.DataFrame(dic)
    dff_res = pd.crosstab(dff_["性别"],dff_[var],margins=True)
    dff_chi = np.array([dff_res.iloc[0][0:(dff_res.shape[1]-1)],dff_res.iloc[1][0:(dff_res.shape[1]-1)]])
    return dff_res,dff_chi,stats.chi2_contingency(dff_chi)[:3],dff_

In [6]:
df_7_res,df_7_chi,df_7_ana,dff_ = cross_analysis2("10、请问您见到的或认为的阻碍生育的因素有哪些","(跳过)","┋")

In [7]:
dff_.to_csv("阻碍生育.csv")

In [8]:
df_7_res

10、请问您见到的或认为的阻碍生育的因素有哪些  其他〖职场歧视（很伤心这居然不是选项之一）〗  其他〖胎儿畸形或者小孩先天性疾病〗  \
性别                                                                   
女                                             1                  1   
男                                             0                  0   
All                                           1                  1   

10、请问您见到的或认为的阻碍生育的因素有哪些  对孩子成长环境的担忧  居住环境压力  抚养压力  教育、培训费用导致经济负担  \
性别                                                                 
女                                70      73   116             68   
男                                85     123   145             93   
All                             155     196   261            161   

10、请问您见到的或认为的阻碍生育的因素有哪些  生育会影响自己实现人生价值  生育痛苦与生育风险  社会上的丁克现象（不生孩子）越来越多  社会政策因素  \
性别                                                                              
女                                   49        117                   8      11   
男                                   35         80                  22      17   
All                                 84        197                  30      28   

10、请问您见到的或认为的阻碍生育的因素有哪些  缺乏家庭照料资源   All  
性别                                       
女                              58   572  
男                              64   664  
All                           122  1236

In [9]:
df_7_chi

array([[  1,   1,  70,  73, 116,  68,  49, 117,   8,  11,  58],
       [  0,   0,  85, 123, 145,  93,  35,  80,  22,  17,  64]],
      dtype=int64)

In [10]:
df_7_ana

(34.04837034743273, 0.00018124577881895748, 10)

## 8、认为提高生育政策

In [33]:
df_8_res,df_8_chi,df_8_ana,dff_ = cross_analysis2("11、请问您认为的可以提高生育意愿的政策有哪些","(跳过)","┋")

In [101]:
df_8_res

11、请问您认为的可以提高生育意愿的政策有哪些  保障女性的充足带薪产假  保障男性的充足带薪育儿假  健全财税政策，加大社会福利补贴力度  其他  \
性别                                                                          
女                                 97            77                 47   0   
男                                 68            56                 54   4   
All                              165           133                101   4   

11、请问您认为的可以提高生育意愿的政策有哪些  其他〖促进男女职场平等〗  加强社会舆论对恋爱、婚姻、亲情、家庭的正面宣传  增强社会养老保障与福利  \
性别                                                                            
女                                   1                       21           14   
男                                   0                       42           30   
All                                 1                       63           44   

11、请问您认为的可以提高生育意愿的政策有哪些  提升社会公共服务质量  降低买房成本（例如对多孩家庭给予买房上的优惠）  降低医疗成本  \
性别                                                                     
女                                23                      101      50   
男                                38                      132     100   
All                              61                      233     150   

11、请问您认为的可以提高生育意愿的政策有哪些  降低托育成本，给与足够的社会照料资源  降低教育成本   All  
性别                                                         
女                                        72     102   605  
男                                        82     138   744  
All                                     154     240  1349

In [35]:
dff_.to_csv("提高生育意愿政策.csv")

In [102]:
df_8_chi

array([[ 97,  77,  47,   0,   1,  21,  14,  23, 101,  50,  72, 102],
       [ 68,  56,  54,   4,   0,  42,  30,  38, 132, 100,  82, 138]],
      dtype=int64)

In [103]:
df_8_ana

(43.38323780170838, 9.313136867718684e-06, 11)

## 9、请问您认为阻碍您生育的因素有哪些

In [105]:
df_9_res,df_9_chi,df_9_ana = cross_analysis2("12、请问您认为阻碍您生育的因素有哪些","(跳过)","┋")

In [106]:
df_9_res

12、请问您认为阻碍您生育的因素有哪些  其他  其他〖不想和异性接触〗  其他〖为什么会有年轻人觉得自己能对另一个人生发展负责〗  \
性别                                                                  
女                     2            0                            1   
男                     0            1                            0   
All                   2            1                            1   

12、请问您认为阻碍您生育的因素有哪些  其他〖同性婚姻不合法〗  其他〖害怕自己有可能会无法避免的像自己的父母一样对待孩子〗  其他〖懒得养〗  \
性别                                                                         
女                              0                              1        0   
男                              1                              0        1   
All                            1                              1        1   

12、请问您认为阻碍您生育的因素有哪些  其他〖我妈妈为了生我放弃当时能更进一步的职位 后来为了照顾我自己出来开店 而且因为婆媳关系导致产后没有得到多好的照顾 我自己是及其担心生孩子的身体负担和潜在危险的 我并不愿意为了生孩子付出自己 但确实妈妈会担心我的养老问题〗  \
性别                                                                                                                                      
女                                                                    1                                                                  
男                                                                    0                                                                  
All                                                                  1                                                                  

12、请问您认为阻碍您生育的因素有哪些  其他〖男女不平等〗  其他〖讨厌小孩〗  对孩子成长环境的担忧  居住环境压力  抚养压力  \
性别                                                                   
女                            1         0          23      15    37   
男                            0         1          13      11    15   
All                          1         1          36      26    52   

12、请问您认为阻碍您生育的因素有哪些  教育、培训费用导致经济负担  生育会影响自己实现人生价值  生育痛苦与生育风险  \
性别                                                             
女                               23             42         52   
男                                8              9         13   
All                             31             51         65   

12、请问您认为阻碍您生育的因素有哪些  社会上的丁克现象（不生孩子）越来越多  社会政策因素  缺乏家庭照料资源  All  
性别                                                              
女                                     2      10         6  216  
男                                     3       2         5   83  
All                                   5      12        11  299

In [110]:
df_9_chi = np.array([df_9_res.iloc[0][9:18],df_9_res.iloc[1][9:18]])
df_9_chi

array([[23, 15, 37, 23, 42, 52,  2, 10,  6],
       [13, 11, 15,  8,  9, 13,  3,  2,  5]], dtype=int64)

In [111]:
stats.chi2_contingency(df_9_chi)[:3]

(13.78861729109177, 0.08744414269799018, 8)

## 10.请问您认为的可以提高生育意愿的政策有哪些

In [113]:
df_10_res,df_10_chi,df_10_ana = cross_analysis2("13、请问您认为的可以提高生育意愿的政策有哪些","(跳过)","┋")

In [117]:
df_10_res

13、请问您认为的可以提高生育意愿的政策有哪些  保障女性的充足带薪产假  保障男性的充足带薪育儿假  健全财税政策，加大社会福利补贴力度  其他  \
性别                                                                          
女                                 43            31                 14   1   
男                                  7             7                  4   0   
All                               50            38                 18   1   

13、请问您认为的可以提高生育意愿的政策有哪些  其他〖人造子宫普及〗  其他〖以上所有〗  其他〖保障女性工作〗  \
性别                                                          
女                                 1         1           1   
男                                 0         0           0   
All                               1         1           1   

13、请问您认为的可以提高生育意愿的政策有哪些  其他〖其实我感觉像我和身边人这一代女生心里已经想好了不生孩子的不管有多好的政策我们也不会生 还不如多弄点养老保障〗  \
性别                                                                                   
女                                                                        1           
男                                                                        0           
All                                                                      1           

13、请问您认为的可以提高生育意愿的政策有哪些  其他〖减少加班现象，有足够的时间可以扶养子女〗  其他〖同性婚姻合法化〗  ...  其他〖没有〗  \
性别                                                             ...           
女                                              1            0  ...       1   
男                                              0            1  ...       0   
All                                            1            1  ...       1   

13、请问您认为的可以提高生育意愿的政策有哪些  其他〖继续限制对女性的教育〗  加强社会舆论对恋爱、婚姻、亲情、家庭的正面宣传  增强社会养老保障与福利  \
性别                                                                              
女                                     1                        5           11   
男                                     0                        5            3   
All                                   1                       10           14   

13、请问您认为的可以提高生育意愿的政策有哪些  提升社会公共服务质量  降低买房成本（例如对多孩家庭给予买房上的优惠）  降低医疗成本  \
性别                                                                     
女                                18                       17      14   
男                                 3                       10       7   
All                              21                       27      21   

13、请问您认为的可以提高生育意愿的政策有哪些  降低托育成本，给与足够的社会照料资源  降低教育成本  All  
性别                                                        
女                                        20      28  211  
男                                         9      13   73  
All                                      29      41  284  

[3 rows x 25 columns]

In [119]:
df_10_chi = np.array([df_10_res.iloc[0][[0,1,2,17,18,19,20,21,22,23,24]],df_10_res.iloc[1][[0,1,2,17,18,19,20,21,22,23,24]]])
df_10_chi

array([[ 43,  31,  14,   5,  11,  18,  17,  14,  20,  28, 211],
       [  7,   7,   4,   5,   3,   3,  10,   7,   9,  13,  73]],
      dtype=int64)

In [120]:
stats.chi2_contingency(df_10_chi)[:3]

(13.133130745918558, 0.21632331426352105, 10)

## 11.1请问您认为自己的婚育观受到下列行为的影响—朋友圈秀恩爱晒娃

In [121]:
df_11_1_res,df_11_1_chi,df_11_1_ana = cross_ananlysis("17、请问您认为自己的婚育观受到下列行为的影响—朋友圈秀恩爱晒娃")

In [122]:
df_11_1_res

17、请问您认为自己的婚育观受到下列行为的影响—朋友圈秀恩爱晒娃  完全不影响  影响极大  影响较大  影响较少  All
21、您的性别                                                       
女                                    88     2    26    84  200
男                                    99     9    27    65  200
All                                 187    11    53   149  400

In [123]:
df_11_1_chi

array([[88,  2, 26, 84],
       [99,  9, 27, 65]], dtype=int64)

In [124]:
df_11_1_ana

(7.543290994549477, 0.056456492642532684, 3)

## 11.2 恋爱相亲育儿综艺

In [125]:
df_11_2_res,df_11_2_chi,df_11_2_ana = cross_ananlysis("17、恋爱相亲育儿综艺")

In [126]:
df_11_2_res

17、恋爱相亲育儿综艺  完全不影响  影响极大  影响较大  影响较少  All
21、您的性别                                  
女               92     4    21    83  200
男              145     4     8    43  200
All            237     8    29   126  400

In [127]:
df_11_2_chi

array([[ 92,   4,  21,  83],
       [145,   4,   8,  43]], dtype=int64)

In [128]:
df_11_2_ana

(30.378319580414736, 1.1489541536104486e-06, 3)

## 11.3 国家的生育政策

In [130]:
df_11_3_res,df_11_3_chi,df_11_3_ana = cross_ananlysis("17、国家的生育政策")

In [131]:
df_11_3_res

17、国家的生育政策  完全不影响  影响极大  影响较大  影响较少  All
21、您的性别                                 
女              56    16    45    83  200
男              94    15    35    56  200
All           150    31    80   139  400

In [132]:
df_11_3_chi

array([[56, 16, 45, 83],
       [94, 15, 35, 56]], dtype=int64)

In [133]:
df_11_3_ana

(16.15352904772956, 0.0010546852663857653, 3)

## 11.4 专家教授发表看法

In [134]:
df_11_4_res,df_11_4_chi,df_11_4_ana = cross_ananlysis("17、专家教授发表看法")

In [135]:
df_11_4_res

17、专家教授发表看法  完全不影响  影响极大  影响较大  影响较少  All
21、您的性别                                  
女              114     1     9    76  200
男              148     3     7    42  200
All            262     4    16   118  400

In [136]:
df_11_4_chi

array([[114,   1,   9,  76],
       [148,   3,   7,  42]], dtype=int64)

In [137]:
df_11_4_ana

(15.45882390994954, 0.0014637131417765108, 3)

## 11.5 娱乐圈情感八卦

In [139]:
df_11_5_res,df_11_5_chi,df_11_5_ana = cross_ananlysis("17、娱乐圈情感八卦")

In [140]:
df_11_5_res

17、娱乐圈情感八卦  完全不影响  影响极大  影响较大  影响较少  All
21、您的性别                                 
女              99     4    22    75  200
男             155     2     5    38  200
All           254     6    27   113  400

In [141]:
df_11_5_chi

array([[ 99,   4,  22,  75],
       [155,   2,   5,  38]], dtype=int64)

In [142]:
df_11_5_ana

(35.83187131107137, 8.12703707455261e-08, 3)

## 11.6 身边人的经历

In [143]:
df_11_6_res,df_11_6_chi,df_11_6_ana = cross_ananlysis("17、身边人的经历")

In [144]:
df_11_6_res

17、身边人的经历  完全不影响  影响极大  影响较大  影响较少  All
21、您的性别                                
女             21    43    90    46  200
男             60    17    77    46  200
All           81    60   167    92  400

In [145]:
df_11_6_chi

array([[21, 43, 90, 46],
       [60, 17, 77, 46]], dtype=int64)

In [146]:
df_11_6_ana

(31.056420492348636, 8.271104378713629e-07, 3)

## 11.7书籍、音乐、绘画等艺术作品

In [148]:
df_11_7_res,df_11_7_chi,df_11_7_ana = cross_ananlysis("17、书籍、音乐、绘画等艺术作品")

In [149]:
df_11_7_res

17、书籍、音乐、绘画等艺术作品  完全不影响  影响极大  影响较大  影响较少  All
21、您的性别                                       
女                    52    11    54    83  200
男                    80    13    48    59  200
All                 132    24   102   142  400

In [150]:
df_11_7_chi

array([[52, 11, 54, 83],
       [80, 13, 48, 59]], dtype=int64)

In [151]:
df_11_7_ana

(10.515339810700208, 0.014657198613959425, 3)

## 12.请问您上网时是否会分享自己的情感、恋爱及婚育观点？

In [158]:
df_12_res,df_12_chi,df_12_ana = cross_ananlysis("17、书籍、音乐、绘画等艺术作品")

TypeError: cross_analysis2() missing 2 required positional arguments: 'useless' and 'splitt'

In [154]:
df_12_res

18、请问您上网时是否会分享自己的情感、恋爱及婚育观点？  不会分享  会公开分享  只和熟悉的朋友分享  All
21、您的性别                                                  
女                               39     26        135  200
男                               55     36        109  200
All                             94     62        244  400

In [155]:
df_12_chi

array([[ 39,  26, 135],
       [ 55,  36, 109]], dtype=int64)

In [156]:
df_12_ana

(7.106799284404289, 0.028627151962558262, 2)

## 13.请问您是否会在朋友圈或社交媒体上秀恩爱？

In [159]:
df_13_res,df_13_chi,df_13_ana = cross_analysis2("19、请问您是否会在朋友圈或社交媒体上秀恩爱？","(跳过)","┋")

In [160]:
df_13_res

19、请问您是否会在朋友圈或社交媒体上秀恩爱？  从不  偶尔  经常  All
性别                                      
女                        15  45   6   66
男                         8  33   6   47
All                      23  78  12  113

In [161]:
df_13_chi

array([[15, 45,  6],
       [ 8, 33,  6]], dtype=int64)

In [162]:
df_13_ana

(0.8046470181067781, 0.6687643593659276, 2)

## 14.请问如果您有孩子（或者您已经有），您会在朋友圈或社交媒体上晒娃吗？

In [163]:
df_14_res,df_14_chi,df_14_ana = cross_analysis2("20、请问如果您有孩子（或者您已经有），您会在朋友圈或社交媒体上晒娃吗？","(跳过)","┋")

In [164]:
df_14_res

20、请问如果您有孩子（或者您已经有），您会在朋友圈或社交媒体上晒娃吗？   不会    会  All
性别                                                 
女                                      61   81  142
男                                      70  106  176
All                                   131  187  318

In [165]:
df_14_chi

array([[ 61,  81],
       [ 70, 106]], dtype=int64)

In [166]:
df_14_ana

(0.21076188312169894, 0.646170902168097, 1)